server:
  servlet:
    context-path: /api
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxx
    password: xxxx
    url: jdbc:mysql://songcm.cn:3306/course_selection?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.spring.CourseElection.model.entity

ENCODE_KEY: xxxx

#logging:
#  level:
#    root: debug